name: Publish to npm

on:
  push:
    branches:
      - vue-2

jobs:
  publish:
    name: Build and publish package
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up nodejs v15
        uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: Install dependencies
        run: npm install
      
      - name: Publish package to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          tag: 'vue-2'
          token: ${{ secrets.NPM_TOKEN }}
